name: Build Flet APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          runner-python-version: "3.11"
          bundled-python-version: "3.11"
